# occasionally might need to clear environment for sanity
rm(list =ls())

# load required packages
library(tidyverse)

# RESONANCE Metadata is very long
# In addition to only calling in subsets of Jen's full export
# Need to increasr the size of the connection buffer
# connection size found by trial error just increase number until read.csv worked

Sys.setenv(VROOM_CONNECTION_SIZE=2000073)

#### Major Raw/Slightly Modified Data Inputs for Downstream Analysis ####
# Call in the full RESONANCE metadata Jan 2023 export from Jen
# change the long column names for easier downstream data wrangling
# these are the airway columns that relate to eczema
# calculate child age in months from the column age of months and days on the assessment
metadata <- read.csv("./raw_data_res/Prioty_Data_013023.csv") %>%
  mutate(studyID = str_pad(.$studyID, 4, pad = "0")) %>% #easier format of studyIDs for joins
  mutate(childAgeMonths = assessmentAgeMonths +
           round(assessmentAgeDays/30.417, digits = 0)) %>% # calculate child age in months
  select_all(~gsub("RedCap_Ess_CPH_Air_Inf..|Redcap_Ess_CPH_Air_EC..|Redcap_Ess_CPH_Air_MC..|Redcap_Ess_CPH_Air_Adol..|BasicFamilyAndChild..", "", .))

## Find the cross-sectional sequenced community infants < 1 year
# This table connects the sampleIDs tot he studyID and timepoint
sequenced <- read.csv("./raw_data_res/Prioty_allmgx.csv") %>%
  rename(studyID = subject) %>% #standardize the name of studyID according to Jen Export
  mutate(studyID = str_pad(.$studyID, 4, pad = "0")) %>% # make the study ID a 4 character string
  filter(childAgeMonths < 13) # only infant samples

# Call in filenames of all the RESONANCE metaphlan profile outputs
# This table was generated by saving all the RES metaphlan output filenames using ls > filenames.txt
filenames <- read_csv("./raw_data_res/filenames.csv", col_names = FALSE) %>%
  separate(X1, into = c("sample", NA), sep = "_" , remove = FALSE) 

# vector of all sequenced RESONANCE samples
sample_list <- filenames$sample

# remove the longitudinal samples
# this table with 151 samples are the infant cross-sectional samples that have been sequenced
seq_cross <- sequenced %>% 
  filter(sample %in% sample_list) %>% # select only the files for which we have metaphlan profiles
  filter(Fecal_EtOH == "F") %>% # don't include ethanol samples
  group_by(studyID) %>% arrange(timepoint, .by_group = TRUE) %>% # early to latest timepoint
  distinct(studyID, .keep_all = TRUE) %>% ungroup() # only keeps the first entry ie earliest timepoint

#cross-sectional sequenced metadata for <1 year infants
seq_metadata <- seq_cross %>% select(sample, studyID, timepoint) %>%
  left_join(., metadata, by = c("studyID","timepoint"))

## Need a cross-sectional version of the metadata

# leave out later time points per studyID to calculate 
# the problem with this table is the first timepoint collected =/= first timepoint sequenced
# therefore this is not the accurate version of the whole community
metadata_1yr <- metadata %>%
  filter(childAgeMonths < 13) %>% 
  group_by(studyID) %>% arrange(timepoint, .by_group = TRUE) %>%
  distinct(studyID, .keep_all = TRUE) %>% ungroup() # get's rid of all longitudinal data 

# Define a cross-sectional whole community that includes only one timepoint per studyID
# But that timepoint should be the timepoint sequenced
# for unsequenced studyIDs it should be the first timepoint collected

# vector of sequenced cross-sectional studyIDs
seq_studyID <- seq_cross$studyID
# filter out the studyIDs already represented by the sequenced community table
# join the table with the seqeunced metadata
comm_metadata <- metadata_1yr %>% filter(!studyID %in% seq_studyID) %>%
  full_join(. , seq_metadata)

#### Export all the relevant metadata ####
# 'raw' metadata for the whole community <1yr
write_csv(seq_metadata)
# 'raw' metadata for the seqeunced community <1yr
write_csv(comm_metadata)

#### Eczema incidence by study ID at any timepoint ####
## Since we are making use of longitudinal data we need to start from the whole metadata sheet ##

# Get out the eczema related columns
# Related Columns determined by reading the intake forms
# [Old Form] Diagnosis list is a checklist of diagnosis for many diseases including eczema 
# [New Forms] Geared at different ages but asks the same question
# 7 or 8: Has the child ever had eczema (also called atopic dermatitis)?
# 7a or 8a: Has a doctor or healthcare provider ever diagnosed the child with eczema or atopic dermatitis?

# Whole community
eczema <- metadata %>% 
  select(studyID, timepoint, ECHOTPCoded, assessmentAgeMonths, 
         Participants..Child_Diagnosis_List, air_inf_d7a, air_inf_d7, 
         air_ec_e8, air_ec_e8a, air_mc_e8, air_mc_e8a, air_adol_e8,
         air_adol_e8a) %>% # this step just limits the columns to make double checking easier; doesn't serve a data transformation purpose
  mutate(diagnosis = ifelse(Participants..Child_Diagnosis_List == "", NA, Participants..Child_Diagnosis_List)) %>%
  mutate(eczema = case_when(air_inf_d7 == 1 | air_inf_d7a == 1 | 
                              air_ec_e8 == 1 | air_ec_e8a == 1 | 
                              air_mc_e8 == 1 | air_mc_e8a == 1 | 
                              air_adol_e8 == 1 | air_adol_e8a == 1 ~ "Yes",
                            air_inf_d7 == 2 | air_inf_d7a == 2 | 
                              air_ec_e8 == 2 | air_ec_e8a == 2 | 
                              air_mc_e8 == 2 | air_mc_e8a == 2 | 
                              air_adol_e8 == 2 | air_adol_e8a == 2 ~ "No",
                            str_detect(diagnosis, "(?i)Eczema") ~ "Yes", #(?i) ignores case sensitivity
                            str_detect(diagnosis, "(?i)Eczema", negate = TRUE) ~ "No")) %>%
  group_by(studyID) %>% arrange(timepoint, .by_group = TRUE) %>%
  mutate(eczema_studyID = case_when(any(eczema == "Yes") ~ "Yes", #yes need to come first to override conflicting No
                                    any(eczema == "No") ~ "No")) %>% ungroup() #if even one sample has eczema they all have eczema
## eczema count
comm_metadata <- eczema %>% select(studyID, timepoint, eczema, eczema_studyID) %>%
  left_join(comm_metadata, ., by = c("studyID", "timepoint")) 
comm_metadata %>% count(eczema_studyID)

# Sequenced community
seq_metadata <- eczema %>% select(studyID, timepoint, eczema, eczema_studyID) %>%
  left_join(seq_metadata, ., by = c("studyID", "timepoint"))
## eczema count  
seq_metadata %>% count(eczema_studyID)

#### Breastfeeding Data ####
## Since we are making use of longitudinal data we need to start from the whole metadata sheet ##

#Make the columns easier to wrangle and double check steps
feeding <- metadata %>% select(studyID, timepoint, ECHOTPCoded, assessmentAgeMonths,
                               starts_with("Redcap_Ess_CHB_IFP.."), starts_with("Redcap_Ess_CHB_CFH.."), 
                               starts_with("BreastfeedingDone.."), starts_with("BreastfeedingStill..")) %>% #limit the table to make wrangling and double-checking easier
  select_if(~!(all(is.na(.)))) %>% #select the columns that are not all entirely NA
  select(-contains(c("participantid", "cohortid", "Discrepancy", "respondent",
                     "formdt", "pin", "protocolid","sequencenum", "siteid", "visitname",
                     "Redcap_Ess_CHB_IFP..StudyID", "Redcap_Ess_CHB_IFP..Timepoint",
                     "Redcap_Ess_CHB_CFH..StudyID", "Redcap_Ess_CHB_CFH..Timepoint"))) %>% # get rid of all columns that are duplicates and preventing getting rid of form name in next step
  select_all(~gsub("Redcap_Ess_CHB_IFP..|Redcap_Ess_CHB_CFH..|BreastfeedingDone..|BreastfeedingStill..", "", .))

## Identify the important columns ##
# description of the column titles for reference:
## From the Form Infant Feeding Practices
#   ifp_b01 = ever breastfed or fed pumped milk
#   ifp_b02 = how long after birth was baby put on breastmilk
#   ifp_b03 = did mother fortify breastmilk with HMF supplement
#   ifp_b04 = did mother completely stop breastfeeding and pumping milk
#   ifp_b04a = did the mother breastfeed for as long as she wanted to
#   ifp_b05 = does the child feed from both breasts while breastfeeding
#   ifp_b08_1 = last 7 days fed breast or pumped milk
#   
#   ifp_c01 = has the child ever been formulafed
#   ifp_c02 = has the child been forluma fed in the last 7 days
#   
#   ifp_d02 = In the past 7 days, has the child been fed anything other than breastmilk/formula
#   ifp_d03 = In the past 7 days, has the child been fed baby cereal
#   ifp_d04 = has the child ever been fed solid food
#   ifp_d05 = In the past 7 days, any food in addition to breastmilk/formula/cereal
#   In the past 7 days, has the child eaten [x]
#   ifp_d06h1 = cereals/starches | ifp_d06i1 = fruit| ifp_d06j1 = vegetables |
#     ifp_d06k1 = meat/chicken/combo | ifp_d06l1 = fish/shellfish | 
#     ifp_d06m1 = eggs | ifp_d06n1 = french fries | ifp_d06o1 = nuts/peanut butter | 
#     ifp_d06p1 = sweets like cake/candy
# 
# ##From the Form Complementary Feeding History [retroactively filled for infants 1st year of life]
#   cfh_01 = was the child ever breastfed [straight/pumped]
#   cfh_04 = has the biological mother completely stopped breastfeeding/pumping
#   cfh_05 = was the child ever fed someone elses breastmilk
#   cfh_06 = was the child ever fed formula
#   cfh_08 = was the child fed food/ beverage other than breastmilk/formula before 6 months
#   when was child first fed [x] (never: 12 months)
#   cfh_12a = breast milk 
#   cfh_12b = pumped breast milk 
#   cfh_12c = formula
#   cfh_12h = other dairy[yoghurt/pudding etc]
#   cfh_12i = other soy food [tofu etc]
#   cfh_12l = baby cereal
#   cfh_12m = other start/carbs
#   cfh_12n = fruit
#   cfh_12o = vegetables
#   cfh_12i = meat/chicken
#   cfh_12i = fish/shellfish
#   cfh_12i = eggs
#   cfh_12i = french fries
#   cfh_12i = nuts/peanut butter
#   cfh_12i = sweets [cake etc]

## Set up Conditionals for Feeding

#number vector representing metadata options
number_list <- c(2,3,4,5,6)

## Breastfeeding Conditionals
A_Present <- feeding$ifp_b01 == 1 | !is.na(feeding$ifp_b02) | feeding$ifp_b03 == 1 | 
  feeding$ifp_b04 == 1 | feeding$ifp_b04a == 1 | feeding$ifp_b05 == 1 |feeding$ifp_b08_1 == 1 |
  feeding$ifp_c01 == 2 | feeding$breastFedPercent == 100.00

A_Past <- feeding$cfh_01 == 1 | feeding$cfh_05 == 1 | feeding$cfh_06 == 2 | 
  feeding$cfh_12a %in% number_list | feeding$cfh_12b %in% number_list | 
  feeding$exclusivelyNursed == "Yes" | feeding$exclusivelyBottlefedBreastmilk == "Yes"


## Formula Feeding Conditionals
B_Present <- feeding$ifp_b01 == 2 | feeding$ifp_c01 == 1 | feeding$ifp_c02 == 1 | 
  feeding$breastFedPercent == 0.00
  
B_Past <- feeding$cfh_01 == 2 | feeding$cfh_06 == 1 | feeding$cfh_12c %in% number_list | 
  feeding$exclusiveFormulaFed == "Yes" | feeding$mostOftenFormulaBrand != ""


## Solids Conditionals
S_Present <- feeding$ifp_d05 == 1 | feeding$ifp_d06h1 == 1 | feeding$ifp_d06i1 == 1 | 
  feeding$ifp_d06j1 == 1 | feeding$ifp_d06k1 == 1 | feeding$ifp_d06l1 == 1 | 
  feeding$ifp_d06m1 == 1 | feeding$ifp_d06n1 == 1 | feeding$ifp_d06o1 == 1 | 
  feeding$ifp_d06p1 == 1 | feeding$ifp_d02 == 1 | feeding$ifp_d03 == 1 | feeding$ifp_d04 == 1 | 
  feeding$solidFood =="Yes"
  

S_Past <- feeding$cfh_12h %in% number_list | feeding$cfh_12i %in% number_list | 
  feeding$cfh_12l %in% number_list | feeding$cfh_12m %in% number_list | 
  feeding$cfh_12n %in% number_list | feeding$cfh_12o %in% number_list |
  feeding$cfh_12p %in% number_list | feeding$cfh_12q %in% number_list | 
  feeding$cfh_12r %in% number_list | feeding$cfh_12s %in% number_list | 
  feeding$cfh_12t %in% number_list | feeding$cfh_12u %in% number_list 

# Whole Community
## feed_present: the feed count
## feed_past:
## feed_past_studyid:
## feedtype: 

feeding <- feeding %>% 
  mutate(feed_present = case_when(A_Present == TRUE & B_Present == TRUE ~ "Mixed",
                                  A_Present == TRUE ~ "BreastFed", B_Present == TRUE ~ "FormulaFed"),
         feed_past = case_when(A_Past == TRUE & B_Past == TRUE ~ "Mixed",
                               A_Past == TRUE ~ "BreastFed", B_Past == TRUE ~ "FormulaFed")) %>%
  group_by(studyID) %>% arrange(timepoint, .by_group = TRUE) %>%
  mutate(feed_past_studyid = case_when(any(feed_past == "Mixed") ~ "Mixed", #yes need to come first to override conflicting No
                                    any(feed_past == "FormulaFed") ~ "FormulaFed",
                                    any(feed_past == "BreastFed") ~ "BreastFed")) %>% ungroup() %>%
  mutate(feedtype = ifelse(!is.na(feed_present), feed_present, 
                           ifelse(!is.na(feed_past), feed_past, feed_past_studyid)))

## Whole Community
feeding_1yr <- left_join(metadata_1yr, feeding, by = c("studyID", "timepoint")) %>%
  select(studyID, timepoint, feedtype)
# count
feeding_1yr %>% count(feedtype)

## Sequenced Community
feedtype_seq <- left_join(sequenced_pruned, feeding, by = c("studyID", "timepoint")) %>%
  select(sample, studyID, timepoint, feedtype)
#count
feedtype_seq %>% count(feedtype)

#### Other Infant Metric ####
# Age
## Whole Community
# Days
mean(metadata_1yr$assessmentAgeMonths*30.417 + metadata_1yr$assessmentAgeDays)


age_months # mean infant age in months
age_months*30.417 # mean infant age in days
metadata_1yr %>% filter(childAgeMonths <= 3) %>% nrow() # no. of sample <= 3mo
metadata_1yr %>% filter(childAgeMonths > 3 & childAgeMonths <= 6 ) %>% nrow() # no. of samples b/w 3 and 6 mo
metadata_1yr %>% filter(childAgeMonths > 6) %>% nrow() # no. of samples b/w 6 and < 13 mo

## Sequenced
# Days
sequenced_pruned$assessmentAgeMonths #*30.417 + sequenced_pruned$assessmentAgeDays)

# Sex
## Whole Community
metadata_1yr %>% count(childGender)
## Sequenced
sequenced_pruned %>% count(childGender)

# Race 
check <- metadata_1yr %>% select(contains("Participants.."))
print(metadata_1yr %>% count(Participants..Merge_Dem_Child_Race), n=22)
metadata_1yr %>% count(Participants..Merge_Dem_Child_Ethnicity)

test <- metadata_1yr %>% rename(race = Participants..Merge_Dem_Child_Race) %>%
  mutate(simple_race = case_when(str_detect(race, "Asian|Other Asian") ~ "Asian"))
    
test %>% count(simple_race)    
    
    all_race == "American Indian or Alaska Native" 
                                 ~ "American Indian", 
                                 all_race == "Asian|Other Asian" ~ "Asian",
                                 all_race == "Black or African American" ~ "Black",
                                 all_race == "Mixed Race" ~ "Mixed Race",
                                 all_race == "Some other race" ~ "Other",
                                 all_race == "White" ~ "White"))
test %>% count(simple_race)
# Height

# Weight
#### Checking that I have the SAMPLEIDs from all MGX runs ####
# The following confirmed I have all the samples we have sequenced as of April 2023
# it calls in its own raw data instead of building off previous wrangling sections

# Call in the 1 year RESONANCE metadata 
## Data is from the January 2023 export from Jen
## Large dataframe - to import into R I subsetted the whole dataset 
## for only infants less than 1 yo in excel first

RES_1yr <- read.csv("./raw_data_res/Prioty_data_013023_12months.csv")

## Call in Kevin's File that has limited amount of information on all our samples
# Most important contains the age in months
all_samples <- read.csv("./raw_data_res/Samples-Everything.csv")

## Call in all the mgx samples from airtable has limited amount of info
# direct csv download of the airtable environment
# Most important are the SampleIDs and age in months
old_mgx <- read.csv("./raw_data_res/Prioty_allmgx.csv")

old_mgx_1year <- old_mgx %>%
  filter(childAgeMonths < 13)
old_mgx_1year <- old_mgx_1year$sample
  ## Call in all the mgx samples from the mgx run that came in march 2023
  # list is from the samples found in IMR-SampleSubmissionSheet_v18(MCCANN_SEP06).xlsx
  # copied and pasted from clipboard using datapasta
  # the list is also saved as a separate text file: Seq_MCCANN_Sep06
  
new_mgx <- c("FG02743", "FG02709", "FG02711", "FG02713", "FG02715", "FG02717", 
              "FG02719", "FG02721", "FG02723", "FG02725", "FG02727", "FG02729", 
              "FG02731", "FG02733", "FG02735", "FG02737", "FG02739", "FG02745", 
              "FG02747", "FG02749", "FG02751", "FG02753", "FG02755", "FG02757", 
              "FG02759", "FG02761", "FG02763", "FG02765", "FG02767", "FG02769", 
              "FG02771", "FG02773", "FG02775", "FG02777", "FG02779", "FG02781", 
              "FG02783", "FG02785", "FG02787", "FG02789", "FG02791", "FG02793", 
              "FG02795", "FG02797", "FG02799", "FG02801", "FG02804", "FG02808", 
              "FG02811", "FG02809", "FG02813", "FG02815", "FG02817", "FG02819", 
              "FG02821", "FG02823", "FG02825", "FG02827", "FG02829", "FG02831", 
              "FG02833", "FG02835", "FG02837", "FG02839", "FG02907", "FG02909", 
              "FG02914", "FG02916", "FG02919", "FG02921", "FG02923", "FG02925", 
              "FG02875", "FG02877", "FG02879", "FG02881", "FG02883", "FG02885", 
              "FG02888", "FG02890", "FG02858", "FG02860", "FG02862", "FG02864", 
              "FG02866", "FG02868", "FG02870", "FG02872", "FG02841", "FG02843", 
              "FG02845", "FG02847", "FG02849", "FG02852", "FG02854", "FG02856", 
              "FG02892", "FG02894", "FG02896", "FG02898", "FG02901", "FG02903", 
              "FG02905", "FG02927")

## Find all the mgx samples

all_mgx <- all_samples %>%
  filter(sample %in% new_mgx | sample %in% old_mgx_1year) %>%
  filter(childAgeMonths < 13) 

# there was no need to do it this way - kevin's airtable mgx file 
# has all the new sequences we received on march 2023 - it is batch 19
# can just filter for childAgeMonths < 13 in the 'old_mgx' file instead

all_mgx <- old_mgx %>%
  filter(childAgeMonths < 13) %>%
  left_join(., all_samples, by = "sample")
